Add initial version of policy for usbguard
USBGuard/usbguard-selinux pull request #1
Opened 2018-09-06 11:39 UTC by wrabcak

Policy sources comes from following pull request:
https://github.com/fedora-selinux/selinux-policy-contrib/pull/26

Original creator of the policy is not responding in PR, so moving this
to usbguard-selinux as we agreed with usbguard developers.

2018-09-06 11:42 UTC, radosroka approved these changes

2018-09-06 12:10 UTC, dkopecek requested changes
Thank you! Please add copyright headers to all the files and mention the also the original author if the contribution is based on his work. Thanks!

2018-09-08 16:21 UTC, dkopecek approved these changes

2018-09-08 16:22 UTC, dkopecek commented
LGTM. Thanks!

2018-09-08 16:22 UTC, merged